import json

data ="[{'Text Chunk': '24Questioning Functionalismscience’s many peer review systems. For example, most scientiﬁc journals acceptarticles for publication based on evaluations by experts. And in most ﬁelds,those experts are not told the identity of the authors whose articles they arereviewing. Although not being told the author’s name does not guaranteehis or her anonymity – because in many ﬁelds a well-connected reviewer canguess the identity of an author from the content of the article – it supportsuniversalism nonetheless, both in practice and as an ideal.Communismstates that scientiﬁc knowledge – the central product of science – is commonly owned.', 'Topic': 'Peer Review'}, {'Text Chunk': 'Originators of ideas can claim recognitionfor their creativity, but cannot dictate how or by whom those ideas are tobe used. Results should be publicized, so that they can be used as widelyas possible. This serves the ends of science, because it allows researchers access to many more ﬁndings than they could hope to create on their own.According to Merton, communism not only promotes the goals of sciencebut reﬂects the fact that science is a social activity, or that scientiﬁc achieve-ments are collectively produced.', 'Topic': 'Scientific Sharing'}, {'Text Chunk': 'Even scientiﬁc discoveries by isolated indi-viduals arise as a result of much earlier research.Disinterestednessis a form of integrity, demanding that scientists disengagetheir interests from their actions and judgments. They are expected to reportresults fully, no matter what theory those results support.', 'Topic': 'Scientific Integrity'}, {'Text Chunk': 'Disinterestednessshould rule out fraud, such as reporting fabricated data, because fraudulentbehavior typically represents the intrusion of interests. And indeed, Mertonbelieves that fraud is rare in science.Organized skepticismis the tendency for the community to disbelieve newideas until they have been well established.', 'Topic': 'Scientific Ethics'}, {'Text Chunk': 'Organized skepticism operatesat two levels. New claims are often greeted by arrays of public challenges. Forexample, even an audience favorably disposed to its claims may ﬁercely ques-tion a presentation at a conference. In addition, scientists may privately reservejudgment on new claims, employing an internalized version of the norm.In addition to these “moral” norms there are “cognitive” norms concerningrules of evidence, the structure of theories, and so on.', 'Topic': 'Scientific Norms'}, {'Text Chunk': 'Because Merton drewa ﬁrm distinction between social and technical domains, cognitive norms arenot a matter for his sociology of science to investigate. In general, Merton’ssociology does not make substantial claims about the intellectual content of science.Institutional norms work in combination with rewards and sanctions, incontexts in which community members are socialized to respond to thoserewards and sanctions.', 'Topic': "Merton's Sociology"}]"
# Convert the string data to a valid JSON format
data = data.replace("'", '"')

# Load the JSON data
json_data = json.loads(data)

# Print the JSON data
data_2 = json.dumps(json_data, indent=4)
print(data_2[0])
